name: Deploy Node.js to anynines

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # 获取代码
      - name: Checkout code
        uses: actions/checkout@v4


      # 安装 Cloud Foundry CLI
      - name: Install Cloud Foundry CLI
        run: |
          mkdir -p $HOME/cf-bin
          cd $HOME/cf-bin

          wget -q "https://packages.cloudfoundry.org/stable?release=linux64-binary" -O cf.tgz

          tar -xzf cf.tgz

          chmod +x cf

          echo "$HOME/cf-bin" >> $GITHUB_PATH

          ./cf version


      # 登录 anynines 德国区
      - name: Login anynines
        run: |
          cf api https://api.de.a9s.eu
          cf auth "${{ secrets.CF_USERNAME }}" "${{ secrets.CF_PASSWORD }}"


      # 部署应用
      - name: Deploy application
        run: |
          cf push
