name: Deploy Node.js to anynines

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # 拉取 GitHub 代码
      - name: Checkout code
        uses: actions/checkout@v4


      # 安装 Cloud Foundry CLI
      - name: Install Cloud Foundry CLI
        run: |
          mkdir -p $HOME/cf-bin
          cd $HOME/cf-bin

          wget -q "https://packages.cloudfoundry.org/stable?release=linux64-binary" -O cf.tgz

          tar -xzf cf.tgz

          chmod +x cf

          echo "$HOME/cf-bin" >> $GITHUB_PATH

          ./cf version


      # 登录 anynines
      - name: Login anynines
        run: |
          cf api https://api.de.a9s.eu
          cf auth "${{ secrets.CF_USERNAME }}" "${{ secrets.CF_PASSWORD }}"


      # 自动选择 Org 和 Space
      - name: Select Org and Space
        run: |

          echo "========== 当前用户 =========="
          cf target


          echo "========== 获取 Org =========="

          cf orgs

          ORG=$(cf orgs | grep -v "Getting orgs" | grep -v "name" | grep -v "^$" | head -n 1)

          echo "使用 Org: $ORG"


          cf target -o "$ORG"


          echo "========== 获取 Space =========="

          cf spaces


          SPACE=$(cf spaces | grep -v "Getting spaces" | grep -v "name" | grep -v "^$" | head -n 1)


          echo "使用 Space: $SPACE"


          cf target -s "$SPACE"


          echo "========== 最终目标 =========="

          cf target


      # 部署应用
      - name: Deploy application
        run: |
          cf push
